---
title: "Research"
description: |
  An overview of my ecology research.
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Participatory science

In my doctoral research, I analyze biodiversity data from participatory science platforms (sometimes called "citizen science" or "community science"). Participatory science is a paradigm by which data are generated on a volunteer basis by anyone who wants to get involved in a decentralized manner. In ecology, participatory data are often opportunistic (meaning, unscheduled) observations of plants or animals. Prominent platforms of interest include [iNaturalist](inaturalist.org) and [eBird](eBird.org).

I am interested in these data along two dimensions. The first of these is: how can we make use of participatory observations of wildlife to better understand the distributions of those wildlife on the landscape? While data submitted to platforms like iNaturalist and eBird are tempting---there's a ton of data, and it's all free to access---the lack of a rigorous sampling structure means that understanding the wildlife without introducing human bias is a statistical challenge.

The second dimension is: what can we learn about human observers from the observations they submit? Participatory science records contain as much information about the people making them (in the aggregate) as they do about the species being observed. For example, we can work with eBird data to ask: when and where are people birding? Are people more likely to travel further from population centers in the summer? Do people prefer more colorful species and individuals, or are they more likely to record a rare species than a common one? Questions about observers' behaviors and preferences seem disconnected from ecology, but in order to handle participatory data correctly we need to deeply understand the process by which they're generated.

#### Select publication: Identifying engaging bird species and traits

[In this paper](doi.org/10.1073/pnas.2110156119), my colleagues and I estimate species-level bias in iNaturalist bird reports compared to eBird. We produce an "overreporting index" for each of 472 species in the United States and interpret that index as a measure of how "engaging" a species is. Colorful, rare, and large birds were more engaging, as epitomized by the overall most engaging bird: the feral Indian peafowl! 

## Species distribution modeling

Understanding how wildlife populations are arranged on the landscape is one of the main goals of wildlife research. "Species distribution modeling" is a term that encompasses research into how wild animals are distributed in space and time, and how those distributions relate to environmental characteristics like habitat type, temperature, and human impacts.

Going from data to inference--for example, from a series of surveys of animal counts to a statistical picture of how those animals use different habitat types--involves statistical modeling.

In my research, I develop statistical solutions for modeling species distributions with data generated in a variety of ways including camera trapping and participatory science. I'm interested in methodological questions about how models operate in general, as well as empirical applications of these models.


#### Select publication: Effects of wildfire diversity on California mammals

[In this project](doi.org/10.1111/ddi.13374), led by collaborator Dr. Brett Furnas at the California Department of Fish and Wildlife, we analyze a camera trap dataset to understand how mammalian carnivores respond to wildfire in California. I helped implement Dr. Furnas' statistical models in a Bayesian framework to generate robust estimates of species' occupancy distributions.

Check out [this article in KQED](https://www.kqed.org/science/1978094/see-california-wildlife-return-to-hidden-cameras-courtesy-of-hidden-cameras) covering the paper.

## Software development

During my Ph.D., I worked as a member of the NIMBLE development team under my advisor and co-creator of NIMBLE, Dr. Perry de Valpine. [NIMBLE](r-nimble.org) is an R extension for building and estimating arbitrary statistical models.

I wrote and maintain the [nimbleEcology](https://cran.r-project.org/web/packages/nimbleEcology/index.html) auxiliary package, which provides additional tools for implementing common models in ecology such as the N-mixture model, the site-occupancy model, and the hidden Markov distribution for multi-state models.

<!-- ## Agroecology -->

<!-- I've had the opportunity to collaborate with colleagues at UC Berkeley to apply my expertise in spatial statistics to a number of interest agricultural problems. As a statistical consultant with [Land Core](https://landcore.org/), I'm working to improve our understanding of the effect of conservation agricultural practices like low-intensity tillage and crop rotation on mitigating risk for farmers. -->

<!-- #### Select publication: Drivers of crop rotation in the Midwest -->

<!-- In this project, led by my colleague Yvonne Socolar, we look for patterns in where Midwestern famers do and don't rotate their crops using a novel Rotational Complexity Index (RCI). The robustness of this study's conclusions depended on a spatial block bootstrap for uncertainty quantification in the presence of spatial autocorrelation. -->
